CaoLiang: Resume Summary
CS2103T-group4-teamD/samplerepo-workflow-practice pull request #3
Opened 2017-09-10 02:17 UTC by caoliangnus

2017-09-11 08:27 UTC, taojiashu commented
The Education and Work experience sections are not formatted correctly. You may want to put a space between "+##" and your header. 
Right now it looks like this:
![image](https://user-images.githubusercontent.com/24546661/30265221-1a9e4e7e-970e-11e7-9284-8a611e9f0029.png)

2017-09-11 09:13 UTC, taojiashu requested changes
Bullet points can be formatted in a more standardised manner. You may want to consider applying bullet points or numerical orders to all of them.

2017-09-11 09:22 UTC, caoliangnus commented
i have changed the format, thank you.

2017-09-13 04:43 UTC, taojiashu approved these changes

2017-09-13 04:43 UTC, merged